language: objective-c
osx_image: xcode12.2

cache:
  directories:
  - Carthage

before_script:
    - ./Scripts/carthage.sh bootstrap --cache-builds

script:
    - set -o pipefail && xcodebuild -project RileyLink.xcodeproj -scheme Shared build -destination 'name=iPhone 8' test | xcpretty
